name: study_forge
description: "A personal app for my personal preferences."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.1+21 # Beta official release

environment:
  sdk: ^3.8.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/sf_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_speed_dial: ^7.0.0
  package_info_plus: ^8.3.0
  flutter_dotenv: ^5.2.1
  sqflite: ^2.0.0+3
  path_provider: ^2.1.5
  uuid: ^4.5.1
  flutter_multi_select_items: ^0.4.3
  markdown: ^7.3.0
  markdown_widget: ^2.3.2+8
  markdown_editor_plus: ^0.2.15 
  font_awesome_flutter: ^10.8.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  lottie: ^3.3.1
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  file_picker: ^8.1.4
  syncfusion_flutter_pdfviewer: ^30.1.38
  share_plus: ^10.1.2
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  device_preview: ^1.2.0
  sqflite_common_ffi: ^2.3.6

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  fonts:
    - family: JBMRegular
      fonts:
        - asset: assets/fonts/JBM-Regular.ttf
    - family: GwendaTimes
      fonts:
        - asset: assets/fonts/GwendaTimes-Regular.ttf
    - family: Petrona
      fonts:
        - asset: assets/fonts/Petrona-Regular.ttf
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf

  assets:
    - assets/system_icons/notification_icon.png
    - assets/sf_logo.png
    - assets/sf_logo_nobg.png
    - assets/lottie/animated_logo.gif
    - assets/.env
    - assets/embers_assets/ember.png
    - assets/embers_assets/ember_head.png

